apiVersion: hostconfig.airshipit.org/v1alpha1
kind: HostConfig
metadata:
  annotations:
    ansible.operator-sdk/reconcile-period: "1d"
  name: check-expiry
spec:
  # Add fields here
  host_groups:
   - name: "kubernetes.io/role"
     values:
      - "master"
  sequential: false
  reexecute: false
  config:
    kubeadm:
      - command: "alpha certs check-expiration"
